FleetTracker/Models/ViewTruckerViewModel.cs
using FleetTracker.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;
using Microsoft.Extensions.Logging;
using System.Text.Json.Serialization;

namespace FleetTracker.ViewModels
{
    public class ViewTruckerViewModel
    {
        private const Double THRESHHOLD_METERS = 150;
        private const int STOP_TIME_MINUTES = 5;
        private const Double DEGREES_TO_METERS = 0.00001;
        private const Double THRESHHOLD = THRESHHOLD_METERS*DEGREES_TO_METERS;
        private const int STOP_TIME_SECONDS = STOP_TIME_MINUTES * 60;
        public Trucker Trucker { get; set; }
        public Manager Manager {get; set; }
        public long UpperTime {get; set; }
        public long DaysDisplay {get; set; }
        [JsonPropertyName("data")]
        public List<Segment> Segments {get; set; }
        public IQueryable<TruckerLog> TruckerLogs {get; set; }
        public List<TruckerLog> AggregatedLogs {get; set; }
        public List<TruckerLog> StopLogs {get; set; }

        public ViewTruckerViewModel(Trucker trucker, 
            IQueryable<TruckerLog> truckerLogs,
            List<Segment>  travelSegments,
            Manager manager,
            long daysDisplay,
            long upperTime)
        {
            Trucker = trucker;
            TruckerLogs = truckerLogs;
            Segments = travelSegments;
            Manager = manager;
            DaysDisplay = daysDisplay;
            UpperTime = upperTime;
        }

        private Double GetDelta(float latA, float lonA, float latB, float lonB)
        {
            return Math.Sqrt(Math.Pow((latA - latB),2) + Math.Pow((lonA - lonB), 2));
        }
        public List<TruckerLog> AggregateNearbyLogs()
        {
            List<TruckerLog> aggregatedLogs = new List<TruckerLog>();
            if (TruckerLogs.Count() == 0) {
                return aggregatedLogs;
            }
            var lst = TruckerLogs.ToList();

            aggregatedLogs.Add(lst[0]);
            var last = aggregatedLogs[0];

            for(var l = 0; l < lst.Count - 1; l++)
            {
                if ((GetDelta(lst[l].Latitude, lst[l].Longitude, last.Latitude,last.Longitude) > THRESHHOLD)
                && (GetDelta(lst[l+1].Latitude, lst[l+1].Longitude, last.Latitude,last.Longitude) > THRESHHOLD))
                {
                    aggregatedLogs.Add(lst[l]);
                    last = lst[l];
                }
            }
            return aggregatedLogs;
        }

        public List<TruckerLog> FindStopPoints()
        {
            List<TruckerLog> stopLogs = new List<TruckerLog>();
            if (AggregatedLogs.Count == 0) {
                return stopLogs;
            }

            int startLogCount = 0;
            int startPinCount = 0;
            for (var i = 0; i < AggregatedLogs.Count-1; i++)
            {
                if ((AggregatedLogs[i+1].TimeStamp - AggregatedLogs[i].TimeStamp) > STOP_TIME_SECONDS)
                {
                    stopLogs.Add(AggregatedLogs[i]);
                    if (i == 0)
                    {
                        startLogCount++;
                    } else {
                        AddSegment(AggregatedLogs[startPinCount], AggregatedLogs[startLogCount], AggregatedLogs[i]);
                        startPinCount = i;
                        startLogCount = i+1;
                    }
                }
            }
            AddSegment(AggregatedLogs[startPinCount], AggregatedLogs[startLogCount], AggregatedLogs[AggregatedLogs.Count-1]);
            return stopLogs;
        }

        void AddSegment(TruckerLog pinStart, TruckerLog logStart, TruckerLog logStop)
        {
            var segLogs = TruckerLogs.Where(x => x.TimeStamp >= logStart.TimeStamp && x.TimeStamp <= logStop.TimeStamp).ToList();
            var segment = new Segment
            {
                PinStart = pinStart,
                LogStart = logStart,
                LogStop = logStop,

                StartTime = logStart.TimeStamp,
                StopTime = logStop.TimeStamp,
                TravelTime = logStop.TimeStamp - logStart.TimeStamp,

                Points = segLogs.Count(),
                MaxSpeed = segLogs.Max(m => m.Speed),
                AvgSpeed = segLogs.Average(m => m.Speed),
                MaxSpeedBreaks = segLogs.Where(x => x.Speed > Manager.MaxSpeed).Count(),
                MaxAccelBreaks = segLogs.Where(x => x.Acceleration > Manager.MaxAccel).Count(),
                Delay = Segments.Count() > 0 ? (logStart.TimeStamp - pinStart.TimeStamp) : null,
                TruckerID = Trucker.ID
            };
            Segments.Add(segment);
        }
    }

    public class Segment
    {
        public long? Delay {get; set; }
        //starting pin, but info won't start logging from here
        public TruckerLog PinStart {get; set; } 
        public TruckerLog LogStart {get; set; }
        public TruckerLog LogStop {get; set; }
        public long StartTime {get; set; }
        public long StopTime {get; set; }
        public long TravelTime {get; set; }
        public int Points {get; set; }
        public float MaxSpeed {get; set; }
        public float AvgSpeed {get; set; }
        public int MaxSpeedBreaks {get; set; }
        public int MaxAccelBreaks {get; set; }
        public int TruckerID {get; set; }
    }
}

FleetTracker/Controllers/FleetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FleetTracker.Models;
using FleetTracker.ViewModels;
using FleetTracker.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace FleetTracker.Controllers
{
    [Authorize]
    public class FleetController : Controller
    {
        private const long DAY_SECONDS = 60*60*24;
        private const long DAY_DISPLAY = 3;
        private readonly ILogger<FleetController> _logger;
        private readonly UserManager<Manager> _userManager;
        private readonly ApplicationDbContext _db;

        public FleetController(ILogger<FleetController> logger, UserManager<Manager> userManager, ApplicationDbContext dbcontext)
        {
            _db = dbcontext;
            _logger = logger;
            _userManager = userManager;
        }
        // GET: /Fleet/Index/
        public async Task<IActionResult> Index()
        {
            var manId = _userManager.GetUserId(User);
            var truckers = _db.Trucker.FromSqlRaw($"SELECT * FROM Trucker WHERE ManagerId = '{manId}'");
            return await Task.Run( () => View(truckers));
        }

        // GET: /Fleet/AddTrucker/
        public IActionResult AddTrucker()
        {
            return View();
        }

        // POST: /Fleet/AddTrucker/
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTrucker(Trucker t)
        {
            if (ModelState.IsValid) {
                t.Manager = await _userManager.GetUserAsync(User);
                _db.Trucker.Add(t);
                _db.SaveChanges();
            }
            return await Task.Run( () => RedirectToAction("Index"));
        }
        // GET: /Fleet/ViewTrucker/
        public async Task<IActionResult> ViewTrucker(string id, string upTillDate, string daysBefore)
        {
            var UpperDate = upTillDate == null ? 
                ((DateTimeOffset)DateTime.Today.AddDays(1)).ToUnixTimeSeconds() 
                : ((DateTimeOffset)DateTime.Parse(upTillDate).AddDays(1)).ToUnixTimeSeconds();
            var DaysBefore = daysBefore == null ? DAY_DISPLAY : Int64.Parse(daysBefore);
            var LowerDate = UpperDate - (DaysBefore*DAY_SECONDS);

            var manager = await _userManager.GetUserAsync(User);
            var viewTruckerViewModel = new ViewTruckerViewModel(
                _db.Trucker.Find(int.Parse(id)),
                 _db.TruckerLog.FromSqlRaw(
                    $"SELECT * FROM TruckerLog WHERE TruckerID = {id} AND TimeStamp > {LowerDate} AND TimeStamp < {UpperDate} ORDER BY TimeStamp ASC"),
                new List<Segment>(), manager, DaysBefore, UpperDate
                );
            viewTruckerViewModel.AggregatedLogs = viewTruckerViewModel.AggregateNearbyLogs();
            viewTruckerViewModel.StopLogs = viewTruckerViewModel.FindStopPoints();
            return View(viewTruckerViewModel);
        }

        // GET: /Fleet/SetRules/
        public async Task<IActionResult> SetRules(Trucker t)
        {
            var manager = await _userManager.GetUserAsync(User);
            return View(manager);
        }

        // POST: /Fleet/SetRules/
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> SetRules(Manager m)
        {
            if (ModelState.IsValid) {
                var manager = await _userManager.GetUserAsync(User);
                manager.MaxSpeed = m.MaxSpeed;
                manager.MinSpeed = m.MinSpeed;
                manager.MaxAccel = m.MaxAccel;
                _db.Manager.Update(manager);
                _db.SaveChanges();
            }
            return await Task.Run( () => RedirectToAction("Index"));
        }
        
        // GET: /Fleet/ResetTrucker/
        public async Task<IActionResult> ResetTrucker(string id)
        {
            var trucker = _db.Trucker.Single(t => t.ID == int.Parse(id));
            trucker.Verified = false;
            _db.Trucker.Update(trucker);
            _db.SaveChanges();

            return await Task.Run( () => RedirectToAction("Index"));
        }

        // GET: /Fleet/ViewTrip/
        public IActionResult ViewTrip(Segment s)
        {
            var logs =  _db.TruckerLog.FromSqlRaw(
                $"SELECT * FROM TruckerLog WHERE TruckerID = {s.TruckerID} AND TimeStamp > {s.StartTime} AND TimeStamp < {s.StopTime} ORDER BY TimeStamp ASC")
                .ToList();
            return View(logs);
        }
        
    }
}

FleetTracker/Views/Fleet/AddTrucker.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Manager> SignInManager
@inject UserManager<Manager> UserManager
@model Trucker

@{
    ViewData["Title"] = "Add Driver";
}

<div class = "page-content">

    <div class="sidebar">
        <partial name="_Fleet" />
    </div>

    <div class="text-center" style="text-align: left;">
        <h1>ADD TRUCKER</h1>
        <form method="POST" style="text-align: left; width=50%">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleNumber"></label>
                <input asp-for="VehicleNumber" class="form-control"/>
                <span asp-validation-for="VehicleNumber" class="text-danger"></span>
            </div>
            <input type="submit" class="btn-primary" value="Save"/>

        </form>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FleetTracker/Views/Fleet/Index.cshtml
@model IQueryable<Trucker>
@{
    ViewData["Title"] = "My Fleet";
}

<div class = "page-content">

    <div class="sidebar">
        <partial name="_Fleet" />
    </div>

    <div class="text-center">
        <h1>MY FLEET</h1>
        <table class="table table-dark table-striped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Vehicle Number</th>
                <th>Verified</th>
            </tr>
        @foreach (var m in @Model)
        {
            <tr>
                <td>@m.ID</td>
                <td>
                    <a class="nav-link" asp-area="" asp-controller="Fleet" asp-action="ViewTrucker" asp-route-id=@m.ID>@m.Name</a>
                </td>
                <td>@m.VehicleNumber</td>
                <td>@m.Verified</td>
                <td>
                    <a class="nav-link" asp-area="" asp-controller="Fleet" asp-action="ResetTrucker" asp-route-id=@m.ID>Reset</a>
                </td>
            </tr>
        }
        </table>
    </div>

</div>

FleetTracker/Views/Fleet/SetRules.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Manager> SignInManager
@inject UserManager<Manager> UserManager
@model Manager

@{
    ViewData["Title"] = "Set Rules";
}

<div class = "page-content">

    <div class="sidebar">
        <partial name="_Fleet" />
    </div>

    <div class="text-center" style="text-align: left;">
        <h1>SET RULES - @Model.UserName</h1>
        <form method="POST" style="text-align: left; width:50%">

            <div class="form-group">
                <label asp-for="MaxSpeed"></label>
                <input asp-for="MaxSpeed" class="form-control"/>
                <span asp-validation-for="MaxSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinSpeed"></label>
                <input asp-for="MinSpeed" class="form-control"/>
                <span asp-validation-for="MinSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxAccel"></label>
                <input asp-for="MaxAccel" class="form-control"/>
                <span asp-validation-for="MaxAccel" class="text-danger"></span>
            </div>
            <input type="submit" class="btn-primary" value="Save"/>
        </form>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FleetTracker/Views/Fleet/ViewTrip.cshtml
@model List<TruckerLog>
@{
    ViewData["Title"] = "View Trucker";
}

<script src="~/lib/chartjs/dist/chart.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<div class = "page-content">

  <div class="sidebar">
    <partial name="_Fleet" />
  </div>

  <div class="text-center">
    <h1>VIEW TRIP - @Model.Count logs:  @DateTimeOffset.FromUnixTimeSeconds(@Model.First().TimeStamp).LocalDateTime - @DateTimeOffset.FromUnixTimeSeconds(@Model.Last().TimeStamp).LocalDateTime </h1>

    <h2>Time plot</h2>
    <div>
      <canvas id="myChart" width="100%" height="30px" style="background-color: #EEF5DB;"></canvas>
    </div>

    <h2>Percentile Distribution</h2>
    <div>
      <canvas id="myPercentile" width="100%" height="30px" style="background-color: #EEF5DB;"></canvas>
    <div>
</div>
<script>
var points = JSON.parse('@Json.Serialize(Model)');

let time = points.map(a => new Date(a.timeStamp*1000).toTimeString().split(" ")[0]);
let speed = points.map(a => a.speed);
let accel = points.map(a => a.acceleration);
let altitude = points.map(a => a.altitude);

const data = {
  labels: time,
  datasets: [{
    label: 'Speed',
    backgroundColor: 'rgb(52, 204, 235)',
    borderColor: 'rgb(52, 204, 235)',
    data: speed
  },
  {
    label: 'Acceleration',
    backgroundColor: 'rgb(255, 0, 0)',
    borderColor: 'rgb(255, 0, 0)',
    data: accel
  },
  {
    label: 'Altitude',
    backgroundColor: 'rgb(0, 255, 0)',
    borderColor: 'rgb(0, 255, 0)',
    data: altitude,
    hidden: true
  }
  ]
};

var config = {
  type: 'line',
  data: data,
  options: {
    scales: {
      x: {
        ticks: {
          font: {
            size: 20,
            weight: 900
          }
        },
        title: {
          display: true,
          text: 'Time',
          font: {
            size: 25,
            weight: 900
          }
        }
      },
      y: {
        ticks: {
          font: {
            size: 20,
            weight: 900
          }
        },
        title: {
          display: true,
          text: 'Speed[km/h]/Accel[m/s^2]/Altitude[m]',
          font: {
            size: 15,
            weight: 900
          }
        }
      }
    }
  }
};

var myChart = new Chart(
    document.getElementById('myChart'),
    config
);

//percentiles
function linspace(start, stop, num, endpoint = true) {
    const div = endpoint ? (num - 1) : num;
    const step = (stop - start) / div;
    return Array.from({length: num}, (_, i) => start + step * i);
}

//deepcopies
speed_c     = jQuery.extend(true, [], speed)
accel_c     = jQuery.extend(true, [], accel)
altitude_c  = jQuery.extend(true, [], altitude) 

var speedSorted  = speed_c.sort(function(a, b){return a - b}); 
var accelSorted  = accel_c.sort(function(a, b){return a - b}); 
var altSorted  = altitude_c.sort(function(a, b){return a - b}); 

var x = linspace(0, 100, speedSorted.length)
x = x.map(x => x.toFixed(1))
console.log(speed)

const percentile_data = {
  labels: x,
  datasets: [{
    label: 'Speed',
    backgroundColor: 'rgb(52, 204, 235)',
    borderColor: 'rgb(52, 204, 235)',
    data: speedSorted
  },
  {
    label: 'Acceleration',
    backgroundColor: 'rgb(255, 0, 0)',
    borderColor: 'rgb(255, 0, 0)',
    data: accelSorted
  },
  {
    label: 'Altitude',
    backgroundColor: 'rgb(0, 255, 0)',
    borderColor: 'rgb(0, 255, 0)',
    data: altSorted,
    hidden: true
  }
  ]
};

const percentile_config = {
  type: 'line',
  data: percentile_data,
  options: {
    scales: {
      x: {
        ticks: {
          font: {
            size: 20,
            weight: 900
          }
        },
        title: {
          display: true,
          text: 'Percentile [%]',
          font: {
            size: 25,
            weight: 900
          }
        }
      },
      y: {
        ticks: {
          font: {
            size: 20,
            weight: 900
          }
        },
        title: {
          display: true,
          text: 'Speed[km/h]/Accel[m/s^2]',
          font: {
            size: 15,
            weight: 900
          }
        }
      }
    }
  }
};

var percentile_plot = new Chart(
    document.getElementById('myPercentile'),
    percentile_config 
);
</script>

FleetTracker/Views/Fleet/ViewTrucker.cshtml
@model FleetTracker.ViewModels.ViewTruckerViewModel
@{
    ViewData["Title"] = "View Trucker";
}

<script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLmGWYDTXI7OofhF5y2_jetVhTOku4pwk&callback=initMap">
</script>

<div class = "page-content">

    <div class="sidebar">
        <partial name="_Fleet" />
    </div>


    <div class="text-center">
        <h1>@Model.Trucker.Name</h1>

        <form method="GET">
            <label for="upTillDate">Date:</label>
            <input id="upTillDate" name="upTillDate" type="date" />

            <label for="daysBefore">Days:</label>
            <input id="daysBefore" name="daysBefore" type="number" value="3"/>

            <input type="submit" class="btn-primary" value="Update"/>
        </form>

        <div id="map"></div>

        <div class="table table-dark table-striped">
            <table style="width: 100%;">
                <tr>
                    <th>Delay(minutes)</th>
                    <th>Departure</th>
                    <th>Arrival</th>
                    <th>Travel Time</th>
                    <th>Logs recorded</th>
                    <th>Max Speed</th>
                    <th>Average Speed</th>
                    <th>Speed lim breaks</th>
                    <th>Accel lim breaks</th>
                    <th>Details</th>
                </tr>

            @for (var i = 0; i < Model.Segments.Count; i++)
            {
                <tr>
                    <td style="color: red;">@(Model.Segments[i].Delay/60)</td>
                    <td>@DateTimeOffset.FromUnixTimeSeconds(Model.Segments[i].StartTime).LocalDateTime</td>
                    <td>@DateTimeOffset.FromUnixTimeSeconds(Model.Segments[i].StopTime).LocalDateTime</td>
                    <td>@(Model.Segments[i].TravelTime/60)</td>
                    <td>@Model.Segments[i].Points</td>
                    <td>@Model.Segments[i].MaxSpeed</td>
                    <td>@Model.Segments[i].AvgSpeed</td>
                    <td>@Model.Segments[i].MaxSpeedBreaks</td>
                    <td>@Model.Segments[i].MaxAccelBreaks</td>
                    <td>@Html.ActionLink("Info", "ViewTrip", "Fleet",@Model.Segments[i],null) </td>
                </tr>
            }
            </table>
        </div>
    </div>

</div>

<script>
var points = JSON.parse('@Json.Serialize(Model.TruckerLogs.ToList())');
var segments = JSON.parse('@Json.Serialize(Model.Segments)');
var upperDate = JSON.parse('@Json.Serialize(Model.UpperTime)');
var daysBefore  = JSON.parse('@Json.Serialize(Model.DaysDisplay)');
var maxSpeed = JSON.parse('@Json.Serialize(Model.Manager.MaxSpeed)');

var uDate = new Date(upperDate*1000).toISOString().split('T')[0];
document.getElementById("upTillDate").value = uDate;
document.getElementById("daysBefore").value = daysBefore;

let markerLabel = 1
//options{log,  arriveTime, departTime, delay}
function makeMarker(options)
{
    var dateOptions = {year:'numeric', month:'numeric', day:'numeric',  hour: '2-digit', minute:'2-digit'};
    var info = "";
    if (options.delay != null) {
        info += "Delay: " + (options.delay/60).toFixed(1) + " minutes\n";
    }

    if (options.arriveTime != null) {
        var arriveDate = new Date(options.arriveTime*1000);
        info += "Arrived: "+ arriveDate.toLocaleTimeString([], dateOptions) + "\n";
    }

    if (options.departTime != null) {
        var departDate = new Date(options.departTime*1000);
        info += "Departure: " + departDate.toLocaleTimeString([], dateOptions) + "\n";
    }

    var m = new google.maps.Marker ({
            position: new google.maps.LatLng ( options.log.latitude, options.log.longitude ),
            title: info,
            label: markerLabel.toString() 
        });
    markerLabel++;
    return m;
}

function sketchRoute(map, seg)
{
    const lineSymbol = {
        path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
    };
    const VALID_COLOR       = "#00FF00";
    const MAX_SPEED_COLOR   = "#FF0000";
    
    var path = [
        {lat: seg.pinStart.latitude, lng: seg.pinStart.longitude},
        {lat: seg.logStart.latitude, lng: seg.logStart.longitude}
    ];

    var line = new google.maps.Polyline({
        path: path,
        geodesic: true,
        strokeColor: VALID_COLOR,
        strokeOpacity: 1.0,
        strokeWeight: 2,
        icons: [
            {
                icon: lineSymbol,
                offset: "100%",
            },
        ],
        map: map,
        title: "lol"
    });

    let segPoints = points.filter(t => t.timeStamp >= seg.logStart.timeStamp && t.timeStamp <= seg.logStop.timeStamp);
    console.log(segPoints);
    for (var i = 1; i < segPoints.length; i++){
        var path = [
            {lat: segPoints[i-1].latitude, lng: segPoints[i-1].longitude},
            {lat: segPoints[i].latitude, lng: segPoints[i].longitude},
        ];

        var color =  segPoints[i].speed <= maxSpeed ? VALID_COLOR : MAX_SPEED_COLOR;

        var line = new google.maps.Polyline({
            path: path,
            geodesic: true,
            strokeColor: color,
            strokeOpacity: 1.0,
            strokeWeight: 2,
            icons: [
                {
                    icon: lineSymbol,
                    offset: "100%",
                },
            ],
            map: map
        });
    }

    return;
}

function initMap(){
    const map = new google.maps.Map(document.getElementById('map'), {
        center: (points.length == 0 ? {lat:-26.2, lng:28} : {lat: points[0].latitude, lng: points[0].longitude }),
        zoom: 11
    });

    var markerOptions, marker;
    for (var i = 0; i < segments.length; i++)
    {
        //logic for adding markers
        if (i == 0){
            markerOptions = {
                log:        segments[i].pinStart, 
                arriveTime: null,
                departTime: segments[i].logStart.timeStamp, 
                delay:      null
            };
            marker = makeMarker(markerOptions);
            marker.setMap(map);
        }
        if (i >= 1) {
            markerOptions = {
                log:        segments[i].pinStart, 
                arriveTime: segments[i].pinStart.timeStamp,
                departTime: segments[i].logStart.timeStamp,
                delay:      segments[i].delay
            };
            marker = makeMarker(markerOptions);
            marker.setMap(map);
        }
        if (i == segments.length-1) {
            markerOptions = {
                log:        segments[i].logStop, 
                arriveTime: segments[i].logStop.timeStamp,
                departTime: null,
                delay:      null
            };
            marker = makeMarker(markerOptions);
            marker.setMap(map);
        }
        sketchRoute(map, segments[i])
    }
}
</script>